-- BAD_AI_READY Part 2: reviewed and executable AI Ready remediation SQL.
--
-- This file is based on the remediation categories generated by the Skill report.
-- The generic draft comments have been replaced with demo-specific business meaning,
-- and the PK/FK/freshness/source candidates have been finalized for this dataset.
--
-- Run as BAD_AI_READY after 02_load_csv.sql.
-- The packaged CSV data is already unique and referentially consistent, so every
-- ENABLE VALIDATE primary-key and foreign-key statement below can be applied directly.

set define off
set verify off
set feedback on
set serveroutput on
set timing on
set pagesize 200
set linesize 240

whenever sqlerror exit sql.sqlcode rollback

begin
  if user <> 'BAD_AI_READY' then
    raise_application_error(-20001, 'Connect as BAD_AI_READY before running this script.');
  end if;
end;
/

prompt ============================================================================
prompt 1. Add freshness and source metadata columns
prompt ============================================================================

declare
  procedure add_column_if_missing(
    p_table_name  in varchar2,
    p_column_name in varchar2,
    p_definition  in varchar2
  ) is
    l_count pls_integer;
  begin
    select count(*)
      into l_count
      from user_tab_columns
     where table_name = upper(p_table_name)
       and column_name = upper(p_column_name);

    if l_count = 0 then
      execute immediate 'alter table "' || upper(p_table_name) || '" add ("' ||
                        upper(p_column_name) || '" ' || p_definition || ')';
      dbms_output.put_line('Added ' || upper(p_table_name) || '.' || upper(p_column_name));
    else
      dbms_output.put_line('Already exists: ' || upper(p_table_name) || '.' || upper(p_column_name));
    end if;
  end;
begin
  add_column_if_missing('AI_DOCUMENTS', 'UPDATED_AT', 'TIMESTAMP(6)');
  add_column_if_missing('AI_DOCUMENTS', 'SOURCE_SYSTEM', 'VARCHAR2(30)');
  add_column_if_missing('CUSTOMER_FEATURES', 'UPDATED_AT', 'TIMESTAMP(6)');
  add_column_if_missing('CUSTOMER_FEATURES', 'SOURCE_SYSTEM', 'VARCHAR2(30)');
  add_column_if_missing('EMPTY_EXPORT', 'UPDATED_AT', 'TIMESTAMP(6)');
  add_column_if_missing('EMPTY_EXPORT', 'SOURCE_SYSTEM', 'VARCHAR2(30)');
  add_column_if_missing('ORPHAN_REGIONS', 'UPDATED_AT', 'TIMESTAMP(6)');
  add_column_if_missing('ORPHAN_REGIONS', 'SOURCE_SYSTEM', 'VARCHAR2(30)');
  add_column_if_missing('RAW_CUSTOMERS', 'UPDATED_AT', 'TIMESTAMP(6)');
  add_column_if_missing('RAW_CUSTOMERS', 'SOURCE_SYSTEM', 'VARCHAR2(30)');
  add_column_if_missing('RAW_ORDERS', 'UPDATED_AT', 'TIMESTAMP(6)');
  add_column_if_missing('RAW_ORDERS', 'SOURCE_SYSTEM', 'VARCHAR2(30)');
  add_column_if_missing('RAW_ORDER_LINES', 'UPDATED_AT', 'TIMESTAMP(6)');
  add_column_if_missing('RAW_ORDER_LINES', 'SOURCE_SYSTEM', 'VARCHAR2(30)');
  add_column_if_missing('SUPPORT_TICKETS', 'UPDATED_AT', 'TIMESTAMP(6)');
  add_column_if_missing('SUPPORT_TICKETS', 'SOURCE_SYSTEM', 'VARCHAR2(30)');
end;
/

declare
  l_sql varchar2(4000);
begin
  update "AI_DOCUMENTS" set "UPDATED_AT" = coalesce("UPDATED_AT", systimestamp), "SOURCE_SYSTEM" = coalesce("SOURCE_SYSTEM", 'PART2_CSV');
  execute immediate 'alter table "AI_DOCUMENTS" modify ("UPDATED_AT" default systimestamp not null, "SOURCE_SYSTEM" default ''PART2_CSV'' not null)';
  update "CUSTOMER_FEATURES" set "UPDATED_AT" = coalesce("UPDATED_AT", systimestamp), "SOURCE_SYSTEM" = coalesce("SOURCE_SYSTEM", 'PART2_CSV');
  execute immediate 'alter table "CUSTOMER_FEATURES" modify ("UPDATED_AT" default systimestamp not null, "SOURCE_SYSTEM" default ''PART2_CSV'' not null)';
  update "EMPTY_EXPORT" set "UPDATED_AT" = coalesce("UPDATED_AT", systimestamp), "SOURCE_SYSTEM" = coalesce("SOURCE_SYSTEM", 'PART2_CSV');
  execute immediate 'alter table "EMPTY_EXPORT" modify ("UPDATED_AT" default systimestamp not null, "SOURCE_SYSTEM" default ''PART2_CSV'' not null)';
  update "ORPHAN_REGIONS" set "UPDATED_AT" = coalesce("UPDATED_AT", systimestamp), "SOURCE_SYSTEM" = coalesce("SOURCE_SYSTEM", 'PART2_CSV');
  execute immediate 'alter table "ORPHAN_REGIONS" modify ("UPDATED_AT" default systimestamp not null, "SOURCE_SYSTEM" default ''PART2_CSV'' not null)';
  update "RAW_CUSTOMERS" set "UPDATED_AT" = coalesce("UPDATED_AT", systimestamp), "SOURCE_SYSTEM" = coalesce("SOURCE_SYSTEM", 'PART2_CSV');
  execute immediate 'alter table "RAW_CUSTOMERS" modify ("UPDATED_AT" default systimestamp not null, "SOURCE_SYSTEM" default ''PART2_CSV'' not null)';
  update "RAW_ORDERS" set "UPDATED_AT" = coalesce("UPDATED_AT", systimestamp), "SOURCE_SYSTEM" = coalesce("SOURCE_SYSTEM", 'PART2_CSV');
  execute immediate 'alter table "RAW_ORDERS" modify ("UPDATED_AT" default systimestamp not null, "SOURCE_SYSTEM" default ''PART2_CSV'' not null)';
  update "RAW_ORDER_LINES" set "UPDATED_AT" = coalesce("UPDATED_AT", systimestamp), "SOURCE_SYSTEM" = coalesce("SOURCE_SYSTEM", 'PART2_CSV');
  execute immediate 'alter table "RAW_ORDER_LINES" modify ("UPDATED_AT" default systimestamp not null, "SOURCE_SYSTEM" default ''PART2_CSV'' not null)';
  update "SUPPORT_TICKETS" set "UPDATED_AT" = coalesce("UPDATED_AT", systimestamp), "SOURCE_SYSTEM" = coalesce("SOURCE_SYSTEM", 'PART2_CSV');
  execute immediate 'alter table "SUPPORT_TICKETS" modify ("UPDATED_AT" default systimestamp not null, "SOURCE_SYSTEM" default ''PART2_CSV'' not null)';
end;
/

prompt ============================================================================
prompt 2. Add reviewed primary keys and foreign keys with validation
prompt ============================================================================

declare
  procedure add_constraint_if_missing(
    p_constraint_name in varchar2,
    p_ddl             in varchar2
  ) is
    l_count pls_integer;
  begin
    select count(*)
      into l_count
      from user_constraints
     where constraint_name = upper(p_constraint_name);

    if l_count = 0 then
      execute immediate p_ddl;
      dbms_output.put_line('Added constraint ' || upper(p_constraint_name));
    else
      dbms_output.put_line('Already exists: ' || upper(p_constraint_name));
    end if;
  end;
begin
  add_constraint_if_missing('PK_ORPHAN_REGIONS',
    'alter table "ORPHAN_REGIONS" add constraint "PK_ORPHAN_REGIONS" primary key ("COUNTRY_CODE") enable validate');
  add_constraint_if_missing('PK_RAW_CUSTOMERS',
    'alter table "RAW_CUSTOMERS" add constraint "PK_RAW_CUSTOMERS" primary key ("CUSTOMER_ID") enable validate');
  add_constraint_if_missing('PK_RAW_ORDERS',
    'alter table "RAW_ORDERS" add constraint "PK_RAW_ORDERS" primary key ("ORDER_ID") enable validate');
  add_constraint_if_missing('PK_RAW_ORDER_LINES',
    'alter table "RAW_ORDER_LINES" add constraint "PK_RAW_ORDER_LINES" primary key ("ORDER_ID", "LINE_NO") enable validate');
  add_constraint_if_missing('PK_AI_DOCUMENTS',
    'alter table "AI_DOCUMENTS" add constraint "PK_AI_DOCUMENTS" primary key ("DOC_ID", "CHUNK_NUMBER") enable validate');
  add_constraint_if_missing('PK_CUSTOMER_FEATURES',
    'alter table "CUSTOMER_FEATURES" add constraint "PK_CUSTOMER_FEATURES" primary key ("CUSTOMER_ID") enable validate');
  add_constraint_if_missing('PK_SUPPORT_TICKETS',
    'alter table "SUPPORT_TICKETS" add constraint "PK_SUPPORT_TICKETS" primary key ("TICKET_ID") enable validate');
  add_constraint_if_missing('PK_EMPTY_EXPORT',
    'alter table "EMPTY_EXPORT" add constraint "PK_EMPTY_EXPORT" primary key ("EXPORT_ID") enable validate');

  add_constraint_if_missing('FK_CUSTOMERS_REGION',
    'alter table "RAW_CUSTOMERS" add constraint "FK_CUSTOMERS_REGION" foreign key ("COUNTRY_CODE") references "ORPHAN_REGIONS" ("COUNTRY_CODE") enable validate');
  add_constraint_if_missing('FK_ORDERS_CUSTOMER',
    'alter table "RAW_ORDERS" add constraint "FK_ORDERS_CUSTOMER" foreign key ("CUSTOMER_ID") references "RAW_CUSTOMERS" ("CUSTOMER_ID") enable validate');
  add_constraint_if_missing('FK_LINES_ORDER',
    'alter table "RAW_ORDER_LINES" add constraint "FK_LINES_ORDER" foreign key ("ORDER_ID") references "RAW_ORDERS" ("ORDER_ID") enable validate');
  add_constraint_if_missing('FK_FEATURES_CUSTOMER',
    'alter table "CUSTOMER_FEATURES" add constraint "FK_FEATURES_CUSTOMER" foreign key ("CUSTOMER_ID") references "RAW_CUSTOMERS" ("CUSTOMER_ID") enable validate');
  add_constraint_if_missing('FK_TICKETS_CUSTOMER',
    'alter table "SUPPORT_TICKETS" add constraint "FK_TICKETS_CUSTOMER" foreign key ("CUSTOMER_ID") references "RAW_CUSTOMERS" ("CUSTOMER_ID") enable validate');
end;
/

prompt ============================================================================
prompt 3. Apply reviewed table comments
prompt ============================================================================
COMMENT ON TABLE "BAD_AI_READY"."AI_DOCUMENTS" IS '社内FAQや運用手順などの検索対象文書を1チャンク1行で保持する。粒度は文書チャンク、更新はデモCSV取込単位。AIはBODY_TEXTを検索対象とし、ORIGIN_URIを回答根拠の参照先として使用する。';
COMMENT ON TABLE "BAD_AI_READY"."CUSTOMER_FEATURES" IS '顧客分析用の特徴量を1顧客1行で保持する。粒度は顧客、更新はデモCSV取込単位。AIはセグメント説明や離反傾向の集計に使用し、個人を断定する用途には使用しない。';
COMMENT ON TABLE "BAD_AI_READY"."EMPTY_EXPORT" IS '外部出力ジョブの定義または結果を保持する予約表。粒度は1出力。デモでは空表であり、AIはデータが存在しないことを前提に扱う。';
COMMENT ON TABLE "BAD_AI_READY"."ORPHAN_REGIONS" IS '国コードと地域名、業務上のリスク区分を保持する参照マスタ。粒度は1国コード、更新はデモCSV取込単位。RAW_CUSTOMERSの国コード解釈に使用する。';
COMMENT ON TABLE "BAD_AI_READY"."RAW_CUSTOMERS" IS '顧客マスタのデモ取込データを1顧客1行で保持する。粒度は顧客、更新はデモCSV取込単位。連絡先や識別情報を含むため、AI回答では必要最小限の項目だけを使用する。';
COMMENT ON TABLE "BAD_AI_READY"."RAW_ORDERS" IS '注文ヘッダーを1注文1行で保持する。粒度は注文、更新はデモCSV取込単位。金額集計ではAMOUNT_TXTを数値へ変換し、通貨はCURRENCY_CODEと組み合わせて解釈する。';
COMMENT ON TABLE "BAD_AI_READY"."RAW_ORDER_LINES" IS '注文明細を1注文内の1明細1行で保持する。粒度は注文IDと明細番号の組合せ。数量、単価、割引率は文字列数値として保持するため、AI集計時は数値変換する。';
COMMENT ON TABLE "BAD_AI_READY"."SUPPORT_TICKETS" IS '顧客サポート問い合わせを1チケット1行で保持する。粒度はチケット、更新はデモCSV取込単位。本文に連絡先が含まれる可能性があるため、AI要約では個人情報を出力しない。';

prompt ============================================================================
prompt 4. Apply reviewed column comments
prompt ============================================================================
COMMENT ON COLUMN "BAD_AI_READY"."AI_DOCUMENTS"."DOC_ID" IS '原文書を識別する数値ID。CHUNK_NUMBERと組み合わせて文書チャンクを一意に識別する。NULL不可。';
COMMENT ON COLUMN "BAD_AI_READY"."AI_DOCUMENTS"."ORIGIN_URI" IS '原文書の参照URI。回答根拠の追跡に使用する合成デモURI。NULL不可。';
COMMENT ON COLUMN "BAD_AI_READY"."AI_DOCUMENTS"."TITLE_TXT" IS '原文書のタイトル。検索結果や回答根拠の表示名に使用する。NULL不可。';
COMMENT ON COLUMN "BAD_AI_READY"."AI_DOCUMENTS"."BODY_TEXT" IS '検索、要約、回答生成の対象となる本文チャンク。NULL不可。合成デモ本文のみを保持する。';
COMMENT ON COLUMN "BAD_AI_READY"."AI_DOCUMENTS"."CHUNK_NUMBER" IS '同一文書内のチャンク順序。1から始まる整数で、DOC_IDと組み合わせて主キーを構成する。';
COMMENT ON COLUMN "BAD_AI_READY"."AI_DOCUMENTS"."EMBEDDING_BLOB_TXT" IS '旧取込形式との互換用に残した埋め込み文字列予約列。本デモではNULLであり、VECTOR型の代替として使用しない。';
COMMENT ON COLUMN "BAD_AI_READY"."AI_DOCUMENTS"."LIFECYCLE_STATE" IS '文書チャンクの利用状態。許容値はREADYまたはARCHIVED。';
COMMENT ON COLUMN "BAD_AI_READY"."AI_DOCUMENTS"."UPDATED_AT" IS 'この行が最後に更新されたデータベース日時。AI回答でデータ鮮度を説明するために使用する。';
COMMENT ON COLUMN "BAD_AI_READY"."AI_DOCUMENTS"."SOURCE_SYSTEM" IS 'この行を提供した元システム識別子。本デモではPART2_CSVを設定する。';
COMMENT ON COLUMN "BAD_AI_READY"."CUSTOMER_FEATURES"."CUSTOMER_ID" IS '特徴量の対象顧客ID。RAW_CUSTOMERS.CUSTOMER_IDを参照し、1顧客1行を一意に識別する。';
COMMENT ON COLUMN "BAD_AI_READY"."CUSTOMER_FEATURES"."CHURN_SCORE_TXT" IS '離反傾向スコアを0.00から0.99の小数文字列で保持する。高いほど離反傾向が高い。';
COMMENT ON COLUMN "BAD_AI_READY"."CUSTOMER_FEATURES"."LIFETIME_VALUE_TXT" IS '顧客生涯価値の推定額を小数文字列で保持する。デモ上の基準通貨額で、集計時は数値変換する。';
COMMENT ON COLUMN "BAD_AI_READY"."CUSTOMER_FEATURES"."SEGMENT_CODE" IS '顧客セグメントコード。許容値はS1、S2、S3、S4。';
COMMENT ON COLUMN "BAD_AI_READY"."CUSTOMER_FEATURES"."FEATURE_NOTES" IS '特徴量の解釈に関する補足。NULLは補足事項なしを表す。';
COMMENT ON COLUMN "BAD_AI_READY"."CUSTOMER_FEATURES"."UPDATED_AT" IS 'この行が最後に更新されたデータベース日時。AI回答でデータ鮮度を説明するために使用する。';
COMMENT ON COLUMN "BAD_AI_READY"."CUSTOMER_FEATURES"."SOURCE_SYSTEM" IS 'この行を提供した元システム識別子。本デモではPART2_CSVを設定する。';
COMMENT ON COLUMN "BAD_AI_READY"."EMPTY_EXPORT"."EXPORT_ID" IS '外部出力を一意に識別する数値ID。表に行が追加された場合の主キー。';
COMMENT ON COLUMN "BAD_AI_READY"."EMPTY_EXPORT"."EXPORT_NAME" IS '外部出力の名称。NULLは名称未設定を表す。';
COMMENT ON COLUMN "BAD_AI_READY"."EMPTY_EXPORT"."PAYLOAD" IS '外部出力の内容または設定を保持するテキスト。NULLは内容未生成を表す。';
COMMENT ON COLUMN "BAD_AI_READY"."EMPTY_EXPORT"."UPDATED_AT" IS 'この行が最後に更新されたデータベース日時。AI回答でデータ鮮度を説明するために使用する。';
COMMENT ON COLUMN "BAD_AI_READY"."EMPTY_EXPORT"."SOURCE_SYSTEM" IS 'この行を提供した元システム識別子。本デモではPART2_CSVを設定する。';
COMMENT ON COLUMN "BAD_AI_READY"."ORPHAN_REGIONS"."COUNTRY_CODE" IS 'ISO 3166-1 alpha-2形式の国コード。RAW_CUSTOMERS.COUNTRY_CODEから参照される主キー。';
COMMENT ON COLUMN "BAD_AI_READY"."ORPHAN_REGIONS"."REGION_NAME" IS '国コードに対応する地域または国の表示名。';
COMMENT ON COLUMN "BAD_AI_READY"."ORPHAN_REGIONS"."RISK_TIER_TXT" IS '業務上のリスク区分。許容値はLOW、MEDIUM、HIGH。法的評価を表すものではない。';
COMMENT ON COLUMN "BAD_AI_READY"."ORPHAN_REGIONS"."UPDATED_AT" IS 'この行が最後に更新されたデータベース日時。AI回答でデータ鮮度を説明するために使用する。';
COMMENT ON COLUMN "BAD_AI_READY"."ORPHAN_REGIONS"."SOURCE_SYSTEM" IS 'この行を提供した元システム識別子。本デモではPART2_CSVを設定する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_CUSTOMERS"."CUSTOMER_ID" IS '顧客を一意に識別する数値ID。主キーであり、注文、特徴量、問い合わせから参照される。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_CUSTOMERS"."FULL_NAME" IS '顧客の表示名。合成データだが個人情報候補として扱い、AI出力では必要な場合だけ使用する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_CUSTOMERS"."EMAIL" IS '顧客のメールアドレス。合成データ。個人情報候補であり、AI回答への直接表示は原則避ける。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_CUSTOMERS"."PHONE" IS '顧客の電話番号。合成データ。個人情報候補であり、AI回答への直接表示は原則避ける。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_CUSTOMERS"."SSN" IS '社会保障番号相当の合成識別子。形式は999-99-9999。高機微情報候補であり、AI回答には表示しない。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_CUSTOMERS"."BIRTHDATE_TXT" IS '顧客の生年月日をYYYY-MM-DD形式の文字列で保持する。個人情報候補であり、年齢分析時だけ利用する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_CUSTOMERS"."COUNTRY_CODE" IS '顧客所在国のISO 3166-1 alpha-2コード。ORPHAN_REGIONS.COUNTRY_CODEを参照する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_CUSTOMERS"."SIGNUP_WHEN_TXT" IS '顧客登録日時をYYYY-MM-DD HH24:MI:SS形式の文字列で保持する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_CUSTOMERS"."STATUS_TXT" IS '顧客状態。許容値はACTIVE、INACTIVE、SUSPENDED。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_CUSTOMERS"."LAST_PURCHASE_AMT" IS '直近購入額を小数点以下2桁の数値文字列で保持する。集計時はTO_NUMBERで数値変換する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_CUSTOMERS"."NOTES" IS '顧客に関する補足メモ。合成データだが連絡先を含む可能性があるためAI出力前に確認する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_CUSTOMERS"."UPDATED_AT" IS 'この行が最後に更新されたデータベース日時。AI回答でデータ鮮度を説明するために使用する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_CUSTOMERS"."SOURCE_SYSTEM" IS 'この行を提供した元システム識別子。本デモではPART2_CSVを設定する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDERS"."ORDER_ID" IS '注文を一意に識別する文字列ID。主キーであり、RAW_ORDER_LINESから参照される。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDERS"."CUSTOMER_ID" IS '注文者の顧客ID。RAW_CUSTOMERS.CUSTOMER_IDを参照する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDERS"."ORDER_TIME_TXT" IS '注文日をYYYY-MM-DD形式の文字列で保持する。日付比較時はTO_DATEで変換する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDERS"."AMOUNT_TXT" IS '注文合計額を小数点以下2桁の数値文字列で保持する。通貨はCURRENCY_CODEで示し、集計時は数値変換する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDERS"."CURRENCY_CODE" IS '注文金額のISO 4217通貨コード。例はJPY、USD、GBP、EUR、SGD、AUD。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDERS"."SHIPPING_POSTAL_CODE" IS '配送先郵便番号。合成データ。所在地情報候補であり、AI回答への表示は必要最小限にする。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDERS"."PAYMENT_CARD_HINT" IS '決済カードの末尾4桁だけを示すマスク済み合成値。機微情報候補であり、AI回答には表示しない。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDERS"."ORDER_PAYLOAD" IS '注文チャネルなどの補助属性を保持するJSON形式テキスト。金額や顧客IDの正本としては使用しない。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDERS"."UPDATED_AT" IS 'この行が最後に更新されたデータベース日時。AI回答でデータ鮮度を説明するために使用する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDERS"."SOURCE_SYSTEM" IS 'この行を提供した元システム識別子。本デモではPART2_CSVを設定する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDER_LINES"."ORDER_ID" IS '明細が属する注文ID。RAW_ORDERS.ORDER_IDを参照し、LINE_NOと組み合わせて主キーを構成する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDER_LINES"."LINE_NO" IS '注文内の明細番号。1から始まる整数で、ORDER_IDとの組合せで一意。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDER_LINES"."SKU" IS '販売商品のSKUコード。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDER_LINES"."QUANTITY_TXT" IS '購入数量を正の整数文字列で保持する。集計時はTO_NUMBERで数値変換する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDER_LINES"."UNIT_PRICE_TXT" IS '商品単価を小数点以下2桁の数値文字列で保持する。通貨は注文ヘッダーのCURRENCY_CODEに従う。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDER_LINES"."DISCOUNT_TXT" IS '明細割引率を0から100の百分率数値文字列で保持する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDER_LINES"."LINE_COMMENT" IS '明細の補足説明。NULLは補足なしを表す。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDER_LINES"."UPDATED_AT" IS 'この行が最後に更新されたデータベース日時。AI回答でデータ鮮度を説明するために使用する。';
COMMENT ON COLUMN "BAD_AI_READY"."RAW_ORDER_LINES"."SOURCE_SYSTEM" IS 'この行を提供した元システム識別子。本デモではPART2_CSVを設定する。';
COMMENT ON COLUMN "BAD_AI_READY"."SUPPORT_TICKETS"."TICKET_ID" IS 'サポート問い合わせを一意に識別する文字列ID。主キー。';
COMMENT ON COLUMN "BAD_AI_READY"."SUPPORT_TICKETS"."CUSTOMER_ID" IS '問い合わせ元の顧客ID。RAW_CUSTOMERS.CUSTOMER_IDを参照する。';
COMMENT ON COLUMN "BAD_AI_READY"."SUPPORT_TICKETS"."SEVERITY_TXT" IS '問い合わせ重大度を1から5の整数文字列で保持する。5が最も重大。';
COMMENT ON COLUMN "BAD_AI_READY"."SUPPORT_TICKETS"."AGENT_EMAIL" IS '担当エージェントの社内メールアドレス。合成データ。個人情報候補として扱う。';
COMMENT ON COLUMN "BAD_AI_READY"."SUPPORT_TICKETS"."REQUESTER_PHONE" IS '問い合わせ元の電話番号。合成データ。個人情報候補であり、AI回答には表示しない。';
COMMENT ON COLUMN "BAD_AI_READY"."SUPPORT_TICKETS"."TICKET_STATUS" IS '問い合わせ状態。許容値はOPEN、IN_PROGRESS、RESOLVED、CLOSED。';
COMMENT ON COLUMN "BAD_AI_READY"."SUPPORT_TICKETS"."PROBLEM_DESCRIPTION" IS '問い合わせ内容の本文。連絡先などを含む可能性があるため、AI要約では個人情報を除外する。';
COMMENT ON COLUMN "BAD_AI_READY"."SUPPORT_TICKETS"."RESOLUTION_TEXT" IS '解決内容。未解決の場合はNULL。解決済み問い合わせではナレッジ候補として利用できる。';
COMMENT ON COLUMN "BAD_AI_READY"."SUPPORT_TICKETS"."UPDATED_AT" IS 'この行が最後に更新されたデータベース日時。AI回答でデータ鮮度を説明するために使用する。';
COMMENT ON COLUMN "BAD_AI_READY"."SUPPORT_TICKETS"."SOURCE_SYSTEM" IS 'この行を提供した元システム識別子。本デモではPART2_CSVを設定する。';

prompt ============================================================================
prompt 5. Remove intentionally broad PUBLIC data grants when present
prompt ============================================================================

declare
begin
  for r in (
    select table_name, privilege
      from user_tab_privs_made
     where grantee = 'PUBLIC'
       and table_name in (
         'AI_DOCUMENTS','CUSTOMER_FEATURES','EMPTY_EXPORT','ORPHAN_REGIONS',
         'RAW_CUSTOMERS','RAW_ORDERS','RAW_ORDER_LINES','SUPPORT_TICKETS'
       )
       and privilege in ('SELECT', 'READ')
  ) loop
    execute immediate 'revoke ' || r.privilege || ' on "' || r.table_name || '" from PUBLIC';
    dbms_output.put_line('Revoked ' || r.privilege || ' on ' || r.table_name || ' from PUBLIC');
  end loop;
end;
/

prompt ============================================================================
prompt 6. Gather optimizer statistics after structural changes
prompt ============================================================================

begin
  for r in (
    select table_name
      from user_tables
     where table_name in (
       'AI_DOCUMENTS','CUSTOMER_FEATURES','EMPTY_EXPORT','ORPHAN_REGIONS',
       'RAW_CUSTOMERS','RAW_ORDERS','RAW_ORDER_LINES','SUPPORT_TICKETS'
     )
     order by table_name
  ) loop
    dbms_stats.gather_table_stats(
      ownname          => user,
      tabname          => r.table_name,
      estimate_percent => dbms_stats.auto_sample_size,
      cascade          => true,
      method_opt       => 'FOR ALL COLUMNS SIZE AUTO',
      no_invalidate    => false
    );
    dbms_output.put_line('Gathered statistics for ' || r.table_name);
  end loop;
end;
/

prompt ============================================================================
prompt 7. Compact post-remediation summary
prompt ============================================================================

column metric format a44
column value format 999999

select 'Target tables' metric, count(*) value
  from user_tables
 where table_name in ('AI_DOCUMENTS','CUSTOMER_FEATURES','EMPTY_EXPORT','ORPHAN_REGIONS','RAW_CUSTOMERS','RAW_ORDERS','RAW_ORDER_LINES','SUPPORT_TICKETS')
union all
select 'Table comments', count(*)
  from user_tab_comments
 where table_type = 'TABLE'
   and table_name in ('AI_DOCUMENTS','CUSTOMER_FEATURES','EMPTY_EXPORT','ORPHAN_REGIONS','RAW_CUSTOMERS','RAW_ORDERS','RAW_ORDER_LINES','SUPPORT_TICKETS')
   and comments is not null
union all
select 'Commented columns', count(*)
  from user_col_comments
 where table_name in ('AI_DOCUMENTS','CUSTOMER_FEATURES','EMPTY_EXPORT','ORPHAN_REGIONS','RAW_CUSTOMERS','RAW_ORDERS','RAW_ORDER_LINES','SUPPORT_TICKETS')
   and comments is not null
union all
select 'Primary keys', count(*)
  from user_constraints
 where table_name in ('AI_DOCUMENTS','CUSTOMER_FEATURES','EMPTY_EXPORT','ORPHAN_REGIONS','RAW_CUSTOMERS','RAW_ORDERS','RAW_ORDER_LINES','SUPPORT_TICKETS')
   and constraint_type = 'P'
union all
select 'Foreign keys', count(*)
  from user_constraints
 where table_name in ('AI_DOCUMENTS','CUSTOMER_FEATURES','EMPTY_EXPORT','ORPHAN_REGIONS','RAW_CUSTOMERS','RAW_ORDERS','RAW_ORDER_LINES','SUPPORT_TICKETS')
   and constraint_type = 'R'
union all
select 'Tables with UPDATED_AT', count(distinct table_name)
  from user_tab_columns
 where table_name in ('AI_DOCUMENTS','CUSTOMER_FEATURES','EMPTY_EXPORT','ORPHAN_REGIONS','RAW_CUSTOMERS','RAW_ORDERS','RAW_ORDER_LINES','SUPPORT_TICKETS')
   and column_name = 'UPDATED_AT'
union all
select 'Tables with SOURCE_SYSTEM', count(distinct table_name)
  from user_tab_columns
 where table_name in ('AI_DOCUMENTS','CUSTOMER_FEATURES','EMPTY_EXPORT','ORPHAN_REGIONS','RAW_CUSTOMERS','RAW_ORDERS','RAW_ORDER_LINES','SUPPORT_TICKETS')
   and column_name = 'SOURCE_SYSTEM'
union all
select 'Tables with optimizer statistics', count(*)
  from user_tables
 where table_name in ('AI_DOCUMENTS','CUSTOMER_FEATURES','EMPTY_EXPORT','ORPHAN_REGIONS','RAW_CUSTOMERS','RAW_ORDERS','RAW_ORDER_LINES','SUPPORT_TICKETS')
   and last_analyzed is not null
union all
select 'Broad PUBLIC SELECT or READ grants', count(*)
  from user_tab_privs_made
 where grantee = 'PUBLIC'
   and table_name in ('AI_DOCUMENTS','CUSTOMER_FEATURES','EMPTY_EXPORT','ORPHAN_REGIONS','RAW_CUSTOMERS','RAW_ORDERS','RAW_ORDER_LINES','SUPPORT_TICKETS')
   and privilege in ('SELECT','READ');

prompt Improvement completed.
prompt Expected values: tables=8, table comments=8, commented columns=68, PK=8, FK=5,
prompt UPDATED_AT=8, SOURCE_SYSTEM=8, statistics=8, broad PUBLIC grants=0.
prompt Rerun oracle-ai-ready-data with profile scan to confirm Mandatory comment gate = pass.
